all:
  hosts:
    server1:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
    server2:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
    server3:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
    server4:
      ansible_host: 192.168.56.13
      ansible_user: vagrant
    server5:
      ansible_host: 192.168.56.14
      ansible_user: vagrant
    server6:
      ansible_host: 192.168.56.15
      ansible_user: vagrant

  children:
    cephmons: 
      hosts:
        server1:
    elasticsearch:
      hosts:
        server3:
    kafka:
      hosts:
        server4:
    mongodb:
      children:
        mongos:
          hosts:
            server5:
    mysql:
      hosts:
        server6:
