docker_config:
  live-restore: true
  log-opts: 
    max-file: "3"
    max-size: 256m
  default-address-pools: 
    - base: "10.10.0.0/16"
      size: 24

additional_services:      
  ceph-exporter:
    image: digitalocean/ceph_exporter:latest
    restart: always
    network_mode: host
    container_name: ceph-exporter
    volumes: 
      - /etc/ceph:/etc/ceph:ro
    command: []