additional_services: 
  mysql_exporter:
    image: prom/mysqld-exporter:v0.14.0
    restart: always
    network_mode: host
    container_name: mysql-exporter
    environment:
      - DATA_SOURCE_NAME=exporter:exporter-pass@(127.0.0.1:3306)/
    command: '--collect.info_schema.tables'